package com.multi.vidulum.trading.app.commands;

import com.multi.vidulum.common.*;
import com.multi.vidulum.shared.cqrs.commands.Command;

import java.time.ZonedDateTime;

public class MakeTradeCommand implements Command {
    UserId userId;
    Broker Broker;
    OriginTradeId originTradeId; // generated by exchange
    Symbol symbol;
    Side side;
    double quantity;
    Money price;
    ZonedDateTime dateTime;
}
