package com.multi.vidulum.trading.app.commands;

import com.multi.vidulum.common.*;
import com.multi.vidulum.portfolio.domain.portfolio.PortfolioId;
import com.multi.vidulum.shared.cqrs.commands.Command;
import lombok.Builder;
import lombok.Value;

import java.time.ZonedDateTime;

@Value
@Builder
public class MakeTradeCommand implements Command {
    UserId userId;
    PortfolioId portfolioId;
    OriginTradeId originTradeId; // generated by exchange

    /**
     * <p>Generated by exchange</p>
     * Filled with {@code PlaceOrderCommand.originOrderId} when particular order has been executed on exchange.
     * Filled with {@code OrderId.notDefined()} in case of making direct trade on exchange.
     */
    OriginOrderId originOrderId;
    Symbol symbol;
    SubName subName;
    Side side;
    Quantity quantity;
    Money price;
    ZonedDateTime originDateTime;
}
